### ISSUE TITLE
Create asset not working

### ISSUE THREAD

**Issue by future-is-present** [bigchaindb/tutorial-crab#11]
Trying to create an asset, when I click on `Execute code` I get the following response

```
Something went wrong!

Network request failed
```
References to IPDB have been changed to BigchainDB test network, but it seems not working

**Comment by jernejpregelj** [comment]
@shahbazn This is possible problem with proxy code that adds auth headers

**Comment by shahbazn** [comment]
@manolodewiner can you please add steps to reproduce exactly what are you trying to do i just posted a transaction with python driver and it went through just fine.

**Comment by future-is-present** [comment]
@shahbazn As you can see I created this issue under the tutorial-crab repository. That means that the create asset that is failing and the button `Execute code` is in the tutorial crab website:
1. Go to 
https://tutorials.bigchaindb.com/crab
2. Scroll down and click on `First step: Create an asset`
3. Click on execute code

**Comment by shahbazn** [comment]
@manolodewiner thanks for the info i checked and as @jernejpregelj mentioned its a config issue with nginx proxy will fix

**Comment by jernejpregelj** [comment]
Closing since this is not relevant anymore.
