### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/tutorial-crab#5]
### Site: https://tutorials.bigchaindb.com/crab/install

1.
> The BigchainDB-ORM module we're going to is supported for NodeJS (version >= 6) as well as the browser.

change to

> The BigchainDB-ORM module we're going to **install** is supported for NodeJS (version >= 6) as well as the browser.

2.
Instead of linking to test.ipdb.io, rather link to developers.ipdb.io

> In the example given below, we connect to the IPDB testnet.

3. 

Maybe mention that an account has to be created on developers.ipdb.io.

### Site: https://tutorials.bigchaindb.com/crab/create

1.
Very cool. One minor thing. I love the dancing crab, but maybe after a few seconds, it would make sense for it to disappear as I was quite interested in what other data was added to my model. I had trouble focusing on it because of that darn :crab: :D!

2.

On second look I'm a bit confused. That's the apparent transaction:

```
{
  "_name": "crab",
  "_schema": "https://example.com/v1/crab",
  "_connection": {
    "path": "https://getstarted.ipdb.io:4443/api/v1/",
    "headers": {},
    "conn": {
      "path": "https://getstarted.ipdb.io:4443/api/v1/",
      "headers": {}
    }
  },
  "_appId": "crabby",
  "txHistory": [
    {
      "inputs": [
        {
          "owners_before": [
            "ARLFk256WjPtzjuuuAczfPVML26djiTsgY7rNJQXzjGo"
          ],
          "fulfills": null,
          "fulfillment": "pGSAIIv05HudtHsQ9aluiPVJ1w4ttgPZxeGvjpUGgdH-Nr9kgUBjUm2EEp0Ah_7KoCAwYsDOVT4TBLkltMbaBHMx8v2X7rj67dsOOD1qUwvjarkmm41tMqO20-isEaNRkVKaELsK"
        }
      ],
      "outputs": [
        {
          "public_keys": [
            "ARLFk256WjPtzjuuuAczfPVML26djiTsgY7rNJQXzjGo"
          ],
          "condition": {
            "details": {
              "type": "ed25519-sha-256",
              "public_key": "ARLFk256WjPtzjuuuAczfPVML26djiTsgY7rNJQXzjGo"
            },
            "uri": "ni:///sha-256;bPfegn_3ZcrmcESgm0c-6BZT6efP5de4dCNBmuPXNGo?fpt=ed25519-sha-256&cost=131072"
          },
          "amount": "1"
        }
      ],
      "operation": "CREATE",
      "metadata": {
        "breed": "coconut crab",
        "color": "blue"
      },
      "asset": {
        "data": {
          "crabby-crab": {
            "schema": "https://example.com/v1/crab",
            "id": "id:crabby:05f9a445-c823-4515-add3-71985f3fb2ad"
          }
        }
      },
      "version": "1.0",
      "id": "941f8e0a6435beb0113457cda595b4948e7e9dacae1a71603c9c5783d95d7bdb"
    }
  ],
  "id": "id:crabby:05f9a445-c823-4515-add3-71985f3fb2ad",
  "data": {
    "breed": "coconut crab",
    "color": "blue"
  }
}
```

but when I look it up:

https://test.ipdb.io/api/v1/transactions/941f8e0a6435beb0113457cda595b4948e7e9dacae1a71603c9c5783d95d7bdb

I think it would make sense to differentiate between the transaction itself and the OrmObject?

```javascript
{
  "orm": {
    "_name": {},
    ...
  }
  transaction: {}
}
```

Generally: Go to any page but the start page e.g. https://tutorials.bigchaindb.com/crab/create
It will show a 403 forbidden.

**Comment by kremalicious** [comment]
> Instead of linking to test.ipdb.io, rather link to developers.ipdb.io

Think by now we can always default linking to ipdb.io so devs can also get some context when needed.
