### ISSUE TITLE
On /create, code doesn't execute and can't advance to retrieve, append, or burn pages

### ISSUE THREAD

**Issue by flowerornament** [bigchaindb/tutorial-crab#6]
On https://tutorials.bigchaindb.com/crab/create, after pressing `Execute code`, I see:

> Something went wrong!
> Network request failed

Clicking on Retrieve, Append, or Burn navbar links causes the router to re-write the URL briefly, but nothing happens.

Errors in console related to Origin and failed AJAX request, but I suspect this is repeatable so ping me if you need more info.

**Comment by flowerornament** [comment]
(In Chrome on Mac both from home and the office.)

**Comment by jernejpregelj** [comment]
The problem is with proxy to ipdb. We're working to get it more stable.

**Comment by flowerornament** [comment]
@jernejpregelj ETA on when this might be fixed?

**Comment by jernejpregelj** [comment]
@msutherl DevOps said today
